### ISSUE TITLE
Cannot find module 'jest-cli'

### ISSUE THREAD

**Issue by ArmorDarks** [yoavniran/gulp-jest-jspm#2]
Hi

Thanks for lib!

We're using only `getJestConfig` method from this task:

```js
const { getJestConfig } = require('gulp-jest-jspm')
```

However, for some reason if `jest-cli` wasn't installed as dependency, it throws an error during import:

```
Error: Cannot find module 'jest-cli'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (J:\Work\Kotsu\github\node_modules\gulp-jest\lib\index.js:7:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

I guess it is because of `gulp-jest` dependency, since `getJestConfig` method doesn't seem to use `jest-cli` anywhere.

**Comment by ArmorDarks** [comment]
I think https://github.com/yoavniran/gulp-jest-jspm/issues/3 will solve that issue.

Though, to me it slightly strange that `jest-cli` specified as dependency of this module, but you still have to install it manually to make it work.

Yeap, I didn't mention that

```shell
npm install jest-cli --save
```

actually solves the issue.

**Comment by yoavniran** [comment]
hi @ArmorDarks 
as you say, #3 should solve this issue indeed.

however, im a little confused because you keep mentioning both jspm-cli and jest-cli in your comments and im not 100% sure which you mean

**Comment by ArmorDarks** [comment]
Hah, I don't know what I was thinking about :D I meant `jest-cli`, of course.
